import { z } from "zod";

const objectIdSchema = z
    .string()
    .trim()
    .regex(
        /^[a-fA-F0-9]{24}$/,
        "Invalid ObjectId"
    );

export const analyzeATSRequestSchema = z.object({

    resumeId: objectIdSchema,

    jobDescription: z
        .string()
        .trim()
        .min(
            50,
            "Job description is too short"
        )
        .max(10000),

});

export type AnalyzeATSRequestInput =
    z.infer<
        typeof analyzeATSRequestSchema
    >;

/**
 * AI Response Schema
 * Validates the JSON returned by the LLM.
 * This contains ONLY the analysis generated by AI,
 * not MongoDB-specific fields like userId or resumeId.
 */
export const atsAIResponseSchema = z.object({

    score: z
        .number()
        .min(0)
        .max(100),

    matchedSkills: z.array(
        z.string()
    ),

    missingSkills: z.array(
        z.string()
    ),

    keywordScore: z
        .number()
        .min(0)
        .max(100),

    experienceScore: z
        .number()
        .min(0)
        .max(100),

    formattingScore: z
        .number()
        .min(0)
        .max(100),

    suggestions: z.array(
        z.string()
    ),

});

export type ATSAIResponse =
    z.infer<
        typeof atsAIResponseSchema
    >;